enum token_type { TOKEN_CREGISTER= 258 ,
				  TOKEN_DREGISTER,
				  TOKEN_SREGISTER,
				  TOKEN_QREGISTER,
				  TOKEN_COMMENT,
				  TOKEN_LOCAL_IDENTIFIER,
				  TOKEN_GLOBAL_IDENTIFIER,
				  TOKEN_LABEL,
				  TOKEN_STRING,
				  TOKEN_PROPERTY,
				  TOKEN_WAVESIZE,
				  
				  /* common keywords */
				  WORKGROUPID,
				  VERSION,
				  GLOBAL,
				  _SAMP,
				  _RWIMG,
				  _ROIMG,
				  ALIGN,
				  _FILE,
				  ARG,
				  KERNARG,
				  FUNCTION,
				  _FBAR,
				  SIGNATURE,
				  BLOCK,
				  ENDBLOCK,
				  BLOCKNUMERIC,
				  BLOCKSTRING,
				  KERNEL,
				  PRAGMA,
				  LABELTARGETS,
				  EXTENSION,
				  EXTERN,
				  STATIC,
				  CONST,
				  PRIVATE,
				  SPILL,
				  GROUP,
				  READONLY,
				  LOC
				 };  // begin from 258 to avoid conflict with ASCII characters
